import enum


class RequestStatus(enum.Enum):
    NEW = "NEW"
    CLARIFICATION = "CLARIFICATION"
    CANCELLED = "CANCELLED"
    CONSULTATION = "CONSULTATION"

    PAYMENT_IN_PROGRESS = "PAYMENT_IN_PROGRESS"
    PAYMENT_VERIFICATION = "PAYMENT_VERIFICATION"
    NO_PAYMENT = "NO_PAYMENT"
    PREPAID = "PREPAID"

    ORDER = "ORDER"
    INVOICE_ISSUED = "INVOICE_ISSUED"
    PAID = "PAID"


class OrderStatus(enum.Enum):
    READY = "READY"
    ACCEPTED = "ACCEPTED"
    CONSULTATION = "CONSULTATION"
    RESCHEDULE = "RESCHEDULE"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"
